name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Unit Test
      run: ./gradlew test

    - name: Run Android Lint
      run: ./gradlew lint

    - name: Build coverage report
      run: ./gradlew jacocoTestReport

    # Codecov Bash uploader
    # See https://docs.codecov.io/docs/about-the-codecov-bash-uploader
    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: ./**/build/reports

    - name: Upload apk file
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
