name: build

on:
  push:
    branches:
      - master

env:
  APP_DIR: app
  LIB_DIR: secure-shared-preferences

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build coverage report
      run: ./gradlew jacocoTestReport

    # Codecov Bash uploader
    # See https://docs.codecov.io/docs/about-the-codecov-bash-uploader
    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # The following generates debug / release APKs and libraries
    - name: Build with Gradle
      run: ./gradlew assemble

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: ./**/build/reports

    - name: Upload apk files
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: ${{ env.APP_DIR }}/build/outputs/apk

    - name: Upload aar files
      uses: actions/upload-artifact@v2
      with:
        name: aar
        path: ${{ env.LIB_DIR }}/build/outputs/aar/
