name: pull_request

on: pull_request

env:
  APP_DIR: app
  LIB_DIR: secure-shared-preferences

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run Unit Test
      run: ./gradlew test

    - name: Run Android Lint
      run: ./gradlew lint

    - name: Run KtLint
      # The option `--continue` is required since we don't want this task interrupted on only
      # one warning / error
      run: ./gradlew --continue ktlintCheck

    - name: Build coverage report
      run: ./gradlew jacocoTestReport

    # Codecov Bash uploader
    # See https://docs.codecov.io/docs/about-the-codecov-bash-uploader
    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # The following generates debug APK and library
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: ./**/build/reports

    - name: Upload apk files
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: ${{ env.APP_DIR }}/build/outputs/apk

    - name: Upload aar files
      uses: actions/upload-artifact@v2
      with:
        name: aar
        path: ${{ env.LIB_DIR }}/build/outputs/aar/
